version: "3.7"

services:
  flask:
    build: ./main
    container_name: main
    restart: always
    environment:
      - APP_NAME=xmeme_backend
    env_file:
      - ./dev.env
    expose:
      - 8080
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"